# REVIEW TEXT ANALYSIS

In [2]:
#beautiful soop 
#scrapy
#array is faster than list


In [20]:
import numpy as np
myarray=np.arange(1000000)

In [21]:
mylist=list(range(1000000))

In [22]:
%time for _ in range(10):myarray2=myarray*2

Wall time: 42 ms


In [4]:
%time for _ in range(10):mylist2=[x*2 for x in mylist]

Wall time: 2.13 s


In [5]:
nd_array=np.array([1,2,3,4])
print(nd_array)
print(type(nd_array))

list1=[2,3,4,5,6]
nda_array=np.array(list1)

print(type(list1))
print(nda_array)

[1 2 3 4]
<class 'numpy.ndarray'>
<class 'list'>
[2 3 4 5 6]


In [6]:
nd_array=np.zeros([2,2])

In [7]:
print(nd_array)

[[0. 0.]
 [0. 0.]]


In [8]:
nd_array=np.ones([3,3])
print(nd_array)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [9]:
nd_array=np.empty([3,3])
print(nd_array)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [10]:
nd_array=np.arange(10)
print(nd_array)

[0 1 2 3 4 5 6 7 8 9]


In [11]:
#initialze and Allocate

In [23]:
nd_array=np.zeros([1,2,3,4]) # 1 row 2 colums 3 2d array
print(nd_array)

[[[[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]

  [[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]]]


In [24]:
nd_array=np.zeros([0,1,2,3,4])
print(nd_array)

[]


In [14]:
list1=[[0,0,0,0],[0,0,0,0],[0,0,0,0]]
print(list1)

[[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]]


In [15]:
list1=np.zeros([3,4])
print(list1)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [16]:
#ANEES AHMED - 03008960038
#hamza 03162052540
#gulraez 03131115563

In [17]:
na= np.zeros([3,4])
print(na.shape)
print(na.dtype)

(3, 4)
float64
