# vectorization

In [11]:
import numpy as np #Vectorize ka function har element pa individual apply karay ga koi bhi function

In [12]:
text='here are some of the things you"ll find in numpy'
prn=print


In [13]:
#create an array with all zeros , having  4 dimenshions , first 5, second 4 ,third 3, fourth 2

In [25]:
arr=np.array([ [
                [0,0,0,0,0],
                [0,0,0,0,0]
               ],
              [
                  [0,0,0,0],
                  [0,0,0,0]
              ],
              [
                  [0,0,0],
                  [0,0,0]
              ],
              [
                  [0,0],
                   [0,0]
              ] 
                ])

In [26]:
print('array',arr)

array [[list([0, 0, 0, 0, 0]) list([0, 0, 0, 0, 0])]
 [list([0, 0, 0, 0]) list([0, 0, 0, 0])]
 [list([0, 0, 0]) list([0, 0, 0])]
 [list([0, 0]) list([0, 0])]]


In [27]:
ndaray=np.zeros([5,4,3,2])

In [18]:
print(ndaray)

[[[[0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]]]


 [[[0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]]]


 [[[0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]]]


 [[[0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]]]


 [[[0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]]]]


In [19]:
#now change the 1st element of 3rd dimenstion with 5

In [30]:
ndaray[:,:,0,:]=5

In [31]:
print(ndaray)

[[[[5. 5.]
   [0. 0.]
   [0. 0.]]

  [[5. 5.]
   [0. 0.]
   [0. 0.]]

  [[5. 5.]
   [0. 0.]
   [0. 0.]]

  [[5. 5.]
   [0. 0.]
   [0. 0.]]]


 [[[5. 5.]
   [0. 0.]
   [0. 0.]]

  [[5. 5.]
   [0. 0.]
   [0. 0.]]

  [[5. 5.]
   [0. 0.]
   [0. 0.]]

  [[5. 5.]
   [0. 0.]
   [0. 0.]]]


 [[[5. 5.]
   [0. 0.]
   [0. 0.]]

  [[5. 5.]
   [0. 0.]
   [0. 0.]]

  [[5. 5.]
   [0. 0.]
   [0. 0.]]

  [[5. 5.]
   [0. 0.]
   [0. 0.]]]


 [[[5. 5.]
   [0. 0.]
   [0. 0.]]

  [[5. 5.]
   [0. 0.]
   [0. 0.]]

  [[5. 5.]
   [0. 0.]
   [0. 0.]]

  [[5. 5.]
   [0. 0.]
   [0. 0.]]]


 [[[5. 5.]
   [0. 0.]
   [0. 0.]]

  [[5. 5.]
   [0. 0.]
   [0. 0.]]

  [[5. 5.]
   [0. 0.]
   [0. 0.]]

  [[5. 5.]
   [0. 0.]
   [0. 0.]]]]


In [87]:
ndaray1=np.zeros([2,3,2,3])

In [88]:
print(ndaray1)

[[[[0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]]]


 [[[0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]]]]


In [89]:
ndaray1[:,:,0,:]=5

In [90]:
print(ndaray1)

[[[[5. 5. 5.]
   [0. 0. 0.]]

  [[5. 5. 5.]
   [0. 0. 0.]]

  [[5. 5. 5.]
   [0. 0. 0.]]]


 [[[5. 5. 5.]
   [0. 0. 0.]]

  [[5. 5. 5.]
   [0. 0. 0.]]

  [[5. 5. 5.]
   [0. 0. 0.]]]]


In [101]:
ndaray2=np.zeros([2,3,2,3])
ndaray2[1,1,0,1:3]=7

In [102]:
print(ndaray2)

[[[[0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]]]


 [[[0. 0. 0.]
   [0. 0. 0.]]

  [[0. 7. 7.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]]]]


In [113]:
ndaray3=np.zeros([2,3,2,3])
ndaray3[1,0:3,0,0:3]=7

In [114]:
print(ndaray3)

[[[[0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]]]


 [[[7. 7. 7.]
   [0. 0. 0.]]

  [[7. 7. 7.]
   [0. 0. 0.]]

  [[7. 7. 7.]
   [0. 0. 0.]]]]


In [121]:
ndaray3=np.zeros([2,3,2,3])
ndaray3[1,0:3,0:2,0:1]=7

In [122]:
print(ndaray3)

[[[[0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]]]


 [[[7. 0. 0.]
   [7. 0. 0.]]

  [[7. 0. 0.]
   [7. 0. 0.]]

  [[7. 0. 0.]
   [7. 0. 0.]]]]


In [138]:
np.fabs(-1) #absolute value always return positive value

1.0

In [136]:
np.abs?
#absolute value always return positive value

In [139]:
np.abs(-1)

1

In [140]:
arr=np.zeros([4])

In [141]:
arr

array([0., 0., 0., 0.])

In [146]:
arr=arr- (1)

In [147]:
arr

array([-1., -1., -1., -1.])

In [148]:
np.where? #reurn where it become true

In [149]:
arr=np.arange(1,10)

In [154]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [151]:
np.where(arr>5)

(array([5, 6, 7, 8], dtype=int64),)

In [152]:
np.where(arr>5,arr,arr*10)

array([10, 20, 30, 40, 50,  6,  7,  8,  9])

In [153]:
arr>5

array([False, False, False, False, False,  True,  True,  True,  True])

In [155]:
arr.cumsum()

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45], dtype=int32)

In [156]:
arr.cumprod()

array([     1,      2,      6,     24,    120,    720,   5040,  40320,
       362880], dtype=int32)

In [157]:
ar2=arr>5

In [158]:
ar2

array([False, False, False, False, False,  True,  True,  True,  True])

In [159]:
ar2.sum()

4

In [160]:
all(arr)

True

In [163]:
any(arr==15)

False

In [164]:
np.unique(arr)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [165]:
np.save('abc.py',arr)

In [168]:
np.load('abc.py.npy')

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [169]:
np.savez('abd',a=arr,b=ar2)

In [170]:
dic = np.load('abd.npz')

In [171]:
dic['a']

array([1, 2, 3, 4, 5, 6, 7, 8, 9])