In [2]:
var='All rights reserved. No part of this book may be reproduced, stored in a retrieval system, or transmitted in any form or by any means, without the prior written permission of the publisher, except in the case of brief quotations embedded in critical articles or reviews. Every effort has been made in the preparation of this book to ensure the accuracy of the information presented. However, the information contained in this book is sold without warranty, either express or implied. Neither the author, nor Packt Publishing, and its dealers and distributors will be held liable for any damages caused or alleged to be caused directly or indirectly by this book.' 

In [3]:
var1='hello'
list1=list(var1)

In [4]:
print(list1)

['h', 'e', 'l', 'l', 'o']


In [5]:
import numpy as np

In [19]:
text='All rights reserved. No part of this book may be reproduced, stored in a retrieval system, or transmitted in any form or by any means, without the prior written permission of the publisher, except in the case of brief quotations embedded in critical articles or reviews. Every effort has been made in the preparation of this book to ensure the accuracy of the information presented. However, the information contained in this book is sold without warranty, either express or implied. Neither the author, nor Packt Publishing, and its dealers and distributors will be held liable for any damages caused or alleged to be caused directly or indirectly by this book. '
var2=np.array([text])

In [21]:
print(text[:10])

All rights


In [22]:
print(var2)

['All rights reserved. No part of this book may be reproduced, stored in a retrieval system, or transmitted in any form or by any means, without the prior written permission of the publisher, except in the case of brief quotations embedded in critical articles or reviews. Every effort has been made in the preparation of this book to ensure the accuracy of the information presented. However, the information contained in this book is sold without warranty, either express or implied. Neither the author, nor Packt Publishing, and its dealers and distributors will be held liable for any damages caused or alleged to be caused directly or indirectly by this book. ']


In [26]:
var3=text.split()
print(var3)

['All', 'rights', 'reserved.', 'No', 'part', 'of', 'this', 'book', 'may', 'be', 'reproduced,', 'stored', 'in', 'a', 'retrieval', 'system,', 'or', 'transmitted', 'in', 'any', 'form', 'or', 'by', 'any', 'means,', 'without', 'the', 'prior', 'written', 'permission', 'of', 'the', 'publisher,', 'except', 'in', 'the', 'case', 'of', 'brief', 'quotations', 'embedded', 'in', 'critical', 'articles', 'or', 'reviews.', 'Every', 'effort', 'has', 'been', 'made', 'in', 'the', 'preparation', 'of', 'this', 'book', 'to', 'ensure', 'the', 'accuracy', 'of', 'the', 'information', 'presented.', 'However,', 'the', 'information', 'contained', 'in', 'this', 'book', 'is', 'sold', 'without', 'warranty,', 'either', 'express', 'or', 'implied.', 'Neither', 'the', 'author,', 'nor', 'Packt', 'Publishing,', 'and', 'its', 'dealers', 'and', 'distributors', 'will', 'be', 'held', 'liable', 'for', 'any', 'damages', 'caused', 'or', 'alleged', 'to', 'be', 'caused', 'directly', 'or', 'indirectly', 'by', 'this', 'book.']


In [25]:
print(var3[:20])

['All', 'rights', 'reserved.', 'No', 'part', 'of', 'this', 'book', 'may', 'be', 'reproduced,', 'stored', 'in', 'a', 'retrieval', 'system,', 'or', 'transmitted', 'in', 'any']


In [27]:
var3=np.array(text.split())
print(var3)

['All' 'rights' 'reserved.' 'No' 'part' 'of' 'this' 'book' 'may' 'be'
 'reproduced,' 'stored' 'in' 'a' 'retrieval' 'system,' 'or' 'transmitted'
 'in' 'any' 'form' 'or' 'by' 'any' 'means,' 'without' 'the' 'prior'
 'written' 'permission' 'of' 'the' 'publisher,' 'except' 'in' 'the' 'case'
 'of' 'brief' 'quotations' 'embedded' 'in' 'critical' 'articles' 'or'
 'reviews.' 'Every' 'effort' 'has' 'been' 'made' 'in' 'the' 'preparation'
 'of' 'this' 'book' 'to' 'ensure' 'the' 'accuracy' 'of' 'the'
 'information' 'presented.' 'However,' 'the' 'information' 'contained'
 'in' 'this' 'book' 'is' 'sold' 'without' 'warranty,' 'either' 'express'
 'or' 'implied.' 'Neither' 'the' 'author,' 'nor' 'Packt' 'Publishing,'
 'and' 'its' 'dealers' 'and' 'distributors' 'will' 'be' 'held' 'liable'
 'for' 'any' 'damages' 'caused' 'or' 'alleged' 'to' 'be' 'caused'
 'directly' 'or' 'indirectly' 'by' 'this' 'book.']


In [28]:
print(len(var3))

110


In [29]:
#variable = store data
#function = returns input run by using 'np.'
#method= 'object.' 
#attribute = attach with method write without backets

In [30]:
print(var3.shape,var3.dtype,var3.ndim)

(110,) <U12 1


In [32]:
d3=np.array([[1,2,3,4],[5,6,7,8]])
print(d3)

[[1 2 3 4]
 [5 6 7 8]]


In [33]:
print(len(d3))
print(d3.size)
print(d3.shape)
print(d3.ndim)

2
8
(2, 4)
2


In [36]:
d4=np.array([[[1,1],[2,2],[3,3]],[[4,4],[5,5],[6,6]],[[7,7],[8,8],[9,9]]])

In [37]:
print(d4)

[[[1 1]
  [2 2]
  [3 3]]

 [[4 4]
  [5 5]
  [6 6]]

 [[7 7]
  [8 8]
  [9 9]]]


In [38]:
print(d4.shape)

(3, 3, 2)


# vectorization

In [43]:
arr=np.array([11,22,33,44,55,65,66,77])

In [44]:
print(arr*6)

[ 66 132 198 264 330 390 396 462]


In [45]:
print(arr[:3]*6) #in list we can not do that

[ 66 132 198]


In [46]:
#equal array operations
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[1,2,3],[4,5,6]])
c=a+b

In [47]:
print(c)

[[ 2  4  6]
 [ 8 10 12]]


In [48]:
d=np.array([1,2,3])

In [49]:
#broadcasting(row size should be same)
print('d array',d)

d array [1 2 3]


In [50]:
print(c.shape,d.shape)

(2, 3) (3,)


In [51]:
print(c+d)

[[ 3  6  9]
 [ 9 12 15]]


In [79]:
import scrapy

   #name of spider
name = 'shopclues'

   #list of allowed domains
allowed_domains = ['www.shopclues.com/mobiles-featured-store-4g-smartphone.html']
   #starting url
start_urls = ['http://www.shopclues.com/mobiles-featured-store-4g-smartphone.html/']
   #location of csv file
custom_settings = {
       'FEED_URI' : 'tmp/shopclues.csv'
   }


       #Extract product information
titles = response.css('img::attr(title)').extract()
images = response.css('img::attr(data-img)').extract()
prices = response.css('.p_price::text').extract()
discounts = response.css('.prd_discount::text').extract()


for item in zip(titles,prices,images,discounts):
    scraped_info ={'title' : item[0],'price' : item[1],'image_urls' : [item[2]], #Set's the url for scrapy to download images'discount' : item[3]}
           

           

SyntaxError: unexpected EOF while parsing (<ipython-input-79-26b15383403c>, line 27)